version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana 

  weather-ui:
    build: ./weather-ui
    ports:
      - "3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
